### ISSUE TITLE
这是企业微信应用吗？

### ISSUE THREAD

**Issue by keepeye** [owent/wxwork_robotd#1]
不是hook或者破解企业微信协议吧

**Comment by owt5008137** [comment]
@keepeye 不是，用的企业微信开放的API

**Comment by jinfagang** [comment]
@owent 可以主动给用户发消息吗?

**Comment by owent** [comment]
> @owent 可以主动给用户发消息吗?

用这个脚本 https://github.com/owent/wxwork_robotd/blob/main/tools/qyapi_wx_send_robot.py 可以

**Comment by jinfagang** [comment]
@owent 这不是rust吗咋有py了

**Comment by owent** [comment]
Rust的这个主要是作为回复的，每条消息是可以返回回复的。
主动发送接口最早是py写的比较省事儿，懒得Rust重写了。

**Comment by jinfagang** [comment]
那如果我想让企微机器人回复私人微信发来的消息，这个rust 
sdk支持吗

**Comment by owent** [comment]
我没测试过微信，也许可以试试看。

**Comment by jinfagang** [comment]
@owent 大佬有空测一波啊，我打算入你的坑，因为我想做一个私人可以访问的机器人，私人微信没有好用的sdk，web协议被禁了。

**Comment by owent** [comment]
我没有打通微信的企业微信账号诶，这个应该是要企业微信的管理员开的吧？

**Comment by jinfagang** [comment]
@owent 管理元开通是啥意思啊，这个sdk里面目前有回复微信消息的能力吗
