### ISSUE TITLE
如何监听机器人被添加好友事件？

### ISSUE THREAD

**Issue by lucasjinreal** [owent/wxwork_robotd#5]

**Comment by owent** [comment]
![image](https://user-images.githubusercontent.com/1209475/189081732-ddc3b302-26f6-4503-a66d-8ec5886d595f.png)
![image](https://user-images.githubusercontent.com/1209475/189081850-8da23794-19f0-44a3-9f4e-81c66af249ab.png)

是指这个？

**Comment by jinfagang** [comment]
@owent 对，不过，再进一步请问一下，对于用户来讲，他可能是从私人微信添加的这个企业微信robot，那么在私人微信里面他可以看到robot的回复吗

**Comment by jinfagang** [comment]
@owent  机器人只需要负责企业微信的接口就行，用户是否在企业微信并不重要，重要的是，机器人是否能response 私人微信给他的消息并且对方能在私人微信接收

**Comment by owent** [comment]
我不确定企业微信和微信的打通是否支持。没测试过。也许可以试试

**Comment by jinfagang** [comment]
@owent 不过在微信里面，是可以加企业微信好友，并且正常收发消息的

**Comment by owent** [comment]
企业微信好友和机器人权限不一样的，机器人权限会低。

**Comment by jinfagang** [comment]
我看到有些人可以做到，私人微信加企业微信联系人，然后我能收到机器人推送的消息，不知道他们怎么做到的，例如这个
![](https://nexthuman.cn/wiki/assets/qrcode.1e88c411.png)

**Comment by owent** [comment]
> 我看到有些人可以做到，私人微信加企业微信联系人，然后我能收到机器人推送的消息，不知道他们怎么做到的，例如这个 ![](https://camo.githubusercontent.com/8a084fc6218e3fe8e291cf4c92f3a8292c7e12d2b05fbc630a81fd1b10aefb26/68747470733a2f2f6e65787468756d616e2e636e2f77696b692f6173736574732f7172636f64652e31653838633431312e706e67)

这种走的可能不是机器人接口，而是用户消息接口。

**Comment by jinfagang** [comment]
你知道这种要怎么做吗？企业微信直接回复消息有啥开源的sdk不

**Comment by owent** [comment]
> 你知道这种要怎么做吗？企业微信直接回复消息有啥开源的sdk不

可以查他们一下开发者文档。他们会提供某些语言的sdk。没有语言sdk的话可能会提供协议文档。这个机器人就是根据机器人的协议文档写的。官方有sdk的，只是没有rust版本

**Comment by jinfagang** [comment]
我发现有个大神做了个这个：https://github.com/eatmoreapple/openwechat 这其实就是私人微信破除了网页版限制。类似于Wechatty的token协议。。。不知道rust这个要怎么做

**Comment by owent** [comment]
我没研究过这个，不过破解协议发消息的话。首先不是公开接口是没有技术支持的，另外这个行为有法律风险。

**Comment by jinfagang** [comment]
那这个用户加企业微信机器人自动回复消息这个功能又可能用rust实现吗
